#!/bin/bash

if [ -z $PYTHON_BIN ]
then
    PYTHON_BIN="/usr/bin/env python"
fi

WEAVE_PATH="$(dirname $0)"

#echo "${PYTHON_BIN} ${WEAVE_PATH}/weaveaccount.py $@"
${PYTHON_BIN} "${WEAVE_PATH}/weaveaccount.py" "$@"
